spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/distributed_metrics}

  kafka:
    topics:
      spark: spark-metrics
      aggregated: aggregated-metrics
    consumer:
      group-id: dev_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

#       TO BE RE-CHECKED
#      properties:
#        spring.json.value.default.type: com.bookmaker.model.dto.EventOutcome
#        spring.json.trusted.packages: com.bookmaker.model
    producer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: record