spring:
  datasource:
    url: jdbc:h2:file:/data/demo;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/db/schema.sql
      data-locations: classpath:/db/data.sql

  kafka:
    topic: event-outcomes
    consumer:
      group-id: dev_group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: com.bookmaker.model.dto.EventOutcome
        spring.json.trusted.packages: com.bookmaker.model
    producer:
      bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    listener:
      ack-mode: record

rocketmq:
  topic: bet-settlements
  name-server: ${SPRING_ROCKETMQ_NAME-SERVER:rocketmq-namesrv:9876}
  producer:
    group: dev_group