spring:
  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://localhost:27017/distributed_metrics}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: dev_group
    listener:
      ack-mode: record
    topics:
      spark: spark-metrics
      aggregated: aggregated-metrics
